version: '2'
services:
    balanceposition-app:
        image: balanceposition
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://balanceposition-mysql:3306/balanceposition?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    balanceposition-mysql:
        extends:
            file: mysql.yml
            service: balanceposition-mysql
